version: "3"

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_mysql
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - "node-network"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    networks:
      - "node-network"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: "always"
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - "node-network"

networks:
  node-network:
    driver: bridge
